EaseHee/AcornSpring2

build.gradle, src/main/java/com/acorn/AcornPrivateApplication.java, src/main/java/com/acorn/api/KakaoRestApi.java, src/main/java/com/acorn/api/NaverBlogSearch.java, src/main/java/com/acorn/api/openfeign/KakaoOpenFeignConfig.java, src/main/java/com/acorn/api/openfeign/KakaoRestOpenFeign.java, src/main/java/com/acorn/api/openfeign/NaverOpenFeign.java, src/main/java/com/acorn/api/openfeign/NaverOpenFeignConfig.java, src/main/java/com/acorn/controller/KakaoRestController.java, src/main/java/com/acorn/controller/NaverController.java, src/main/resources/application.properties
스프링 클라우드 프레임워크 내 OpenFeign 라이브러리 활용.
API 연동 목적
=> feat: Spring Cloud OpenFeign

src/main/java/com/acorn/model/EateriesModel.java
=> feat: DB INSERT 주석 처리

build.gradle, src/main/java/com/acorn/common/ResponseCode.java, src/main/java/com/acorn/common/ResponseMessage.java, src/main/java/com/acorn/config/SecurityConfig.java, src/main/java/com/acorn/controller/AuthController.java, src/main/java/com/acorn/dto/JwtDto.java, src/main/java/com/acorn/dto/LoginRepsonseDto.java, src/main/java/com/acorn/dto/LoginRequestDto.java, src/main/java/com/acorn/dto/MembersDto.java, src/main/java/com/acorn/dto/RegisterRequestDto.java, src/main/java/com/acorn/dto/RegisterResponseDto.java, src/main/java/com/acorn/dto/ResponseDto.java, src/main/java/com/acorn/entity/MembersDetail.java, src/main/java/com/acorn/entity/MembersMain.java, src/main/java/com/acorn/entity/RefreshToken.java, src/main/java/com/acorn/jwt/JwtAuthenticationFilter.java, src/main/java/com/acorn/jwt/JwtProvider.java, src/main/java/com/acorn/process/AuthProcess.java, src/main/java/com/acorn/process/AuthProcessImpl.java, src/main/java/com/acorn/process/CertificationGenerator.java, src/main/java/com/acorn/process/MailProcess.java, src/main/java/com/acorn/process/RefreshTokenProcess.java, src/main/java/com/acorn/repository/MembersDetailRepository.java, src/main/java/com/acorn/repository/MembersMainRepository.java, src/main/java/com/acorn/repository/RefreshTokenRepository.java, src/main/resources/application.properties
=> feat : Auth

src/main/java/com/acorn/aspect/GlobalExceptionAspect.java
상세 설정 시 반환 타입 내 ResponseEntity의 body메서드 인자 데이터 수정
=> feat: 전역 예외 처리 Aspect 추가

src/main/java/com/acorn/api/KakaoRestApi.java, src/main/java/com/acorn/api/openfeign/KakaoRestOpenFeign.java, src/main/java/com/acorn/aspect/GlobalExceptionAspect.java, src/main/java/com/acorn/controller/KakaoRestController.java, src/main/java/com/acorn/dto/AddressResponse.java, src/main/java/com/acorn/exception/NotFoundException.java
=> feat: 경위도 주소를 도로명 주소로 변환

src/main/java/com/acorn/jwt/JwtAuthenticationFilter.java, src/main/java/com/acorn/jwt/JwtUtil.java
=> refactor: 코드 주석 수정

src/main/java/com/acorn/api/openfeign/KakaoLoginOpenFeign.java, src/main/java/com/acorn/api/openfeign/KakaoOpenFeignConfig.java, src/main/java/com/acorn/api/openfeign/KakaoRestOpenFeign.java, src/main/java/com/acorn/api/openfeign/KakaoUserOpenFeign.java, src/main/java/com/acorn/controller/KakaoLoginController.java, src/main/java/com/acorn/controller/KakaoRestController.java, src/main/java/com/acorn/dto/KakaoDto.java, src/main/java/com/acorn/process/AddressProcess.java, src/main/java/com/acorn/process/KakaoLoginProcess.java, src/main/java/com/acorn/process/KakaoUserProcess.java
=> feat: 카카오 간편 로그인 - 사용자 정보 가져오기 API

src/main/java/com/acorn/controller/EateriesController.java, src/main/java/com/acorn/controller/EateriesMainController.java, src/main/java/com/acorn/controller/MypageController.java, src/main/java/com/acorn/controller/ReviewController.java, src/main/java/com/acorn/dto/EateriesDto.java, src/main/java/com/acorn/dto/ReviewRequestDto.java, src/main/java/com/acorn/dto/ReviewResponseDto.java, src/main/java/com/acorn/entity/Eateries.java, src/main/java/com/acorn/entity/Reviews.java, src/main/java/com/acorn/process/ReviewsProcess.java, src/main/java/com/acorn/repository/ReviewsRepository.java, src/main/resources/application.properties
=> feat:리뷰 전반 수정

src/main/java/com/acorn/controller/CategoryController.java, src/main/java/com/acorn/dto/CategoriesFilterDto.java, src/main/java/com/acorn/dto/CategoryGroupsFilterDto.java, src/main/java/com/acorn/process/CategoryProcess.java
카테고리 대분류 DTO 내부에 소분류 DTO를 포함하여 카테고리 대분류 데이터만 반환해도 특정 대분류 하위의 모든 소분류 데이터에 접근할 수 있게끔 재구성함.
=> fix: 카테고리 필터를 위한 카테고리 응답 데이터 구성 변경.

src/main/java/com/acorn/controller/CategoryController.java
main/category -> main/category/filter로 URI 변경
=> fix: 카테고리 필터 REST API URI 변경

src/main/java/com/acorn/entity/Comments.java, src/main/java/com/acorn/process/CommentsProcess.java
=> 댓글 CRUD BE 로직 설계 완료

src/main/java/com/acorn/config/SecurityConfig.java, src/main/java/com/acorn/controller/MembersController.java, src/main/java/com/acorn/dto/MembersDto.java, src/main/java/com/acorn/dto/RegisterRequestDto.java, src/main/java/com/acorn/entity/Members.java, src/main/java/com/acorn/jwt/JwtAuthenticationFilter.java, src/main/java/com/acorn/jwt/JwtUtil.java, src/main/java/com/acorn/process/AuthProcessImpl.java, src/main/java/com/acorn/process/CustomUserDetailService.java, src/main/java/com/acorn/process/MembersProcessImpl.java
리프레쉬 토큰으로 엑세스 토큰 재발급, 권한 설정 기능 개발
=> feat : 엑세스 토큰 재발급, 권한 설정 개발

src/main/java/com/acorn/controller/EateriesMainController.java, src/main/java/com/acorn/entity/Categories.java, src/main/java/com/acorn/entity/Eateries.java, src/main/java/com/acorn/process/CategoryProcess.java, src/main/java/com/acorn/process/EateriesMainProcess.java, src/main/java/com/acorn/repository/EateriesRepository.java, src/main/java/com/acorn/utils/PageUtil.java
PageRequest.of(page, size)의 페이지 zero-base로 인한 문제 해결.
=> fix: 페이징 번호 문제 해결

src/main/java/com/acorn/api/openfeign/KakaoRestOpenFeign.java, src/main/java/com/acorn/controller/EateriesMainController.java, src/main/java/com/acorn/dto/location/LocationSplitDto.java, src/main/java/com/acorn/dto/openfeign/kakao/blog/BlogDocumentsDto.java, src/main/java/com/acorn/dto/openfeign/kakao/blog/BlogMetaDto.java, src/main/java/com/acorn/dto/openfeign/kakao/blog/BlogRequestDto.java, src/main/java/com/acorn/dto/openfeign/kakao/blog/BlogResponseDto.java, src/main/java/com/acorn/dto/openfeign/kakao/geo/location/GeoLocationResponseDto.java, src/main/java/com/acorn/dto/openfeign/kakao/image/ImageDocumentDto.java, src/main/java/com/acorn/dto/openfeign/kakao/image/ImageMetaDto.java, src/main/java/com/acorn/dto/openfeign/kakao/image/ImageRequestDto.java, src/main/java/com/acorn/dto/openfeign/kakao/image/ImageResponseDto.java, src/main/java/com/acorn/dto/openfeign/kakao/keyword/KeywordDocumentDto.java, src/main/java/com/acorn/dto/openfeign/kakao/keyword/KeywordMetaDto.java, src/main/java/com/acorn/dto/openfeign/kakao/keyword/KeywordRequestDto.java, src/main/java/com/acorn/dto/openfeign/kakao/keyword/KeywordResponseDto.java, src/main/java/com/acorn/exception/BadAlgorithmException.java, src/main/java/com/acorn/exception/api/DuplicatedInDBException.java, src/main/java/com/acorn/exception/category/NoCategoryFoundException.java, src/main/java/com/acorn/process/CategoryProcess.java, src/main/java/com/acorn/process/EateriesMainProcess.java, src/main/java/com/acorn/process/EateriesWithApiProcess.java
=> refactor: REST API URL 변화.

src/main/java/com/acorn/controller/FavoritesController.java, src/main/java/com/acorn/controller/ImageProxyController.java, src/main/java/com/acorn/process/FavoritesProcess.java, src/main/java/com/acorn/repository/FavoritesRepository.java
=> feat: favorite

src/main/java/com/acorn/controller/FavoritesController.java
main/eateries/{eateryNo}/favorites/count 로 요청 시 오류 발생..
main/eateries/{eateryNo}/favorites 으로 요청명 변경
=> fix: FavoritesController 요청 API 수정

src/main/java/com/acorn/process/MembersProcessImpl.java
=> feat: 프로필 수정 추가 개발

src/main/java/com/acorn/jwt/JwtAuthenticationFilter.java, src/main/java/com/acorn/jwt/JwtUtil.java, src/main/java/com/acorn/process/AuthProcessImpl.java, src/main/java/com/acorn/process/MembersProcessImpl.java
=> fix: 회원탈퇴 로직 수정

src/main/java/com/acorn/process/AuthProcessImpl.java
feat : 비활성화 계정에 대한 응답 로직 추가 개발
=> feat : 비활성화 계정에 대한 응답 로직 추가 개발

src/main/java/com/acorn/process/AuthProcessImpl.java
테스트할 방법이 없어 실제로 리프레시가 DB에 두 개가 생기지 않는지 확인할 길이 없음.
=> fix: 리프레시 생성 관련 버그 방지 코드 추가.

src/main/java/com/acorn/dto/MembersDto.java, src/main/java/com/acorn/dto/RegisterResponseDto.java, src/main/java/com/acorn/process/AuthProcessImpl.java
=> feat : 이메일 패턴 유효성 검증 추가 개발
